# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NavMenu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("top", "Top"), ("footer", "Footer")],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "menu",
                    wagtail.fields.StreamField(
                        (
                            (
                                "heading",
                                wagtail.blocks.CharBlock(classname="full title"),
                            ),
                            ("paragraph", wagtail.blocks.RichTextBlock()),
                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                        )
                    ),
                ),
            ],
        ),
    ]
