# Generated by Django 2.2.7 on 2019-11-11 16:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail_nav_menus.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_nav_menus', '0002_auto_20190911_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenu',
            name='site',
            field=models.ForeignKey(default=wagtail_nav_menus.models.site_default_id, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
    ]
